[workspace]
resolver = "3"
members = ["mbconf"]


package.license-file = "LICENSE"
package.homepage = "https://github.com/piksel/mbconf"
package.repository = "https://github.com/piksel/mbconf"
package.readme = "README.md"